// AUTO-GENERATED by social-drafts/blotato/facebook/build-artifact.mjs. Do not edit by hand.
// Source of truth: FB-PLAYBOOK.md, REELS-24.md, fb-content-bank.json.
// Regenerate: cd social-drafts/blotato/facebook && node build-artifact.mjs
export const FB_PLAYBOOK = {
  "built": "2026-07-23",
  "postWindow": {
    "start": "2026-07-27",
    "end": "2026-10-03"
  },
  "startHere": [
    {
      "h": "Your Page vs a new Group (you need both)",
      "paras": [
        "They are two different tools with two different jobs, and this is the thing almost everyone gets wrong."
      ],
      "list": {
        "type": "ul",
        "items": [
          "**Your business Page is your storefront window.** The Reels and the 30 scheduled posts go here. It is how strangers find you. Facebook shows a plain Page post to roughly 1-2% of your followers, plus whoever a Reel reaches, which is the whole reason Reels matter more than anything else.",
          "**A new Group is your living room.** Teardown Tuesday, Steal This Thursday, and Win Friday live here. Members see it in their feed as a group they chose to join, which gets far more reach than a Page post ever will. This is where the community forms and where the buyers come from.",
          "**They feed each other.** Every Reel on your Page pins a comment pointing to the Group. Every Group ritual becomes a Reel on your Page. You post to the Page to get found, and you run the Group to turn followers into a community. So yes, start the new Group. It is the part that makes this a community instead of a billboard."
        ]
      }
    },
    {
      "h": "Where each piece of this deck goes",
      "paras": [],
      "list": {
        "type": "ul",
        "items": [
          "**Reels (24):** your Page, posted by hand from the phone so you get trending audio.",
          "**Posts (30):** your Page, auto-scheduled through Blotato once the Page ID is set.",
          "**The Group tab:** used once, to create the new Group. Paste the five blocks.",
          "**The Growth tab:** your daily habits, most of them done in other people's groups."
        ]
      }
    },
    {
      "h": "How to find members (in order, fastest first)",
      "paras": [],
      "list": {
        "type": "ol",
        "items": [
          "**Invite your Page followers, day one.** In Page settings there is a \"link a group\" option. Link it, then invite your existing followers to join. This is your warmest, fastest seed.",
          "**Pin the Group link on every Reel.** A Reel reaches strangers. The pinned comment sends the ones who found it useful into the Group. This is the engine, and it is why the Reels come first.",
          "**Invite everyone who reacts to a post.** On any Page post with reactions, click the reaction count, then Invite. Most people never do this. It is the single most underused free growth lever on Facebook.",
          "**Serve in 10 other groups, 10 minutes a day (weeks 1 to 4).** Find groups where owners ask questions. Give the single best, most complete answer in the thread, with no link and no pitch. Your profile does the selling. People click the name of whoever just helped them.",
          "**Personally invite your first 20.** Past clients, local owners, business friends. A group needs a floor of 20 to 30 real people before it feels alive and strangers will stay."
        ]
      }
    },
    {
      "h": "Launch order (do it exactly like this)",
      "paras": [],
      "list": {
        "type": "ol",
        "items": [
          "**Create the Group first** and link it to your Page. The pinned Reel comments need somewhere to point, so the Group has to exist before you post.",
          "**Paste the five Group blocks** from the Group tab: name, description, join questions, rules, and the pinned \"Start Here\" post.",
          "**Set FB_PAGE_ID** so the 30 posts can schedule, and set GROUP_URL so the ritual first-comments resolve.",
          "**Batch-shoot Reels 1 to 8** and post R1 on Monday alongside the manifesto text post.",
          "**Invite your Page followers and your first 20** the same day, so the Group is never empty when the first stranger arrives."
        ]
      }
    }
  ],
  "reels": [
    {
      "n": 1,
      "title": "The After-Hours Test",
      "batch": "Weeks 1 to 2",
      "pillar": "The Leak",
      "shot": "FACE",
      "length": "30s",
      "onScreenHook": "Call your own business. Right now.",
      "hook": "Call your own business right now. From your cell phone. After hours.",
      "script": [
        "Most owners have never done this and most are horrified by what they hear. A phone that rings eleven times. A voicemail box that says the wrong hours. A greeting recorded by an employee who quit in 2023.",
        "Your customer does this at 6pm on a Tuesday, standing in a flooded kitchen, and they do not leave a message. They call the next person on the list.",
        "That's not a marketing problem. You already paid for that lead. You just dropped it.",
        "Go call your business. Tell me what you heard."
      ],
      "beats": [
        "Call your own business. Right now.",
        "Rings 11 times",
        "Wrong hours on the voicemail",
        "They don't leave a message. They call the next guy.",
        "You already PAID for that lead."
      ],
      "caption": "Do this today. Call your own business from your cell, after hours, and listen to the whole thing the way a customer would. Then tell me in the comments what you heard. I'll tell you how to fix it. 👇",
      "ask": null
    },
    {
      "n": 2,
      "title": "Missed-Call Text-Back",
      "batch": "Weeks 1 to 2",
      "pillar": "Steal This",
      "shot": "BOTH",
      "length": "35s",
      "onScreenHook": "The highest-ROI switch in small business",
      "hook": "The single highest-return switch in small business takes four minutes to turn on and almost nobody has done it.",
      "script": [
        "It's called missed-call text-back. When someone calls and you don't pick up, an automatic text goes out inside sixty seconds. \"Sorry we missed you, this is Dave's Plumbing, what do you need?\"",
        "Here's why it works. People who would never leave a voicemail will absolutely answer a text. You just recovered a pile of jobs you were losing without knowing it.",
        "Almost every phone system and CRM already does this. You are probably paying for it right now. Go turn it on.",
        "That's free. I'm not selling you anything. Go do it."
      ],
      "beats": [
        "Missed-call text-back",
        "Auto-text in 60 seconds",
        "People who won't leave a voicemail WILL text back",
        "You already pay for this feature",
        "4 minutes. Go."
      ],
      "caption": "Free one. Missed-call text-back is probably already sitting in the phone system or CRM you pay for every month, switched off. Turn it on this afternoon. Come back and tell me what it caught.",
      "ask": null
    },
    {
      "n": 3,
      "title": "The Review Link Nobody Fixes",
      "batch": "Weeks 1 to 2",
      "pillar": "Steal This",
      "shot": "SCREEN",
      "length": "25s",
      "onScreenHook": "This is why you only have 12 reviews",
      "hook": "This is why you have twelve reviews and your competitor has three hundred.",
      "script": [
        "When you ask a happy customer for a review, you send them to your website. They have to find the reviews section, click through to Google, sign in, find the button. Four taps. They quit on tap two.",
        "Go to your Google Business Profile, hit \"Ask for reviews,\" and copy that short link. That one opens the review box directly. One tap, they're typing.",
        "Same customers. Same work. One better link. Owners who fix this go from a dozen reviews to a hundred in a season."
      ],
      "beats": [
        "[screen record the actual GBP \"Ask for reviews\" flow] \"4 taps = they quit",
        "1 tap = they type",
        "Google Business Profile",
        "Ask for reviews",
        "copy link"
      ],
      "caption": "Screen recording of the exact fix. Takes 90 seconds. Your review count is not a reflection of your work, it's a reflection of how many taps you're asking for.",
      "ask": null
    },
    {
      "n": 4,
      "title": "You Don't Have a Lead Problem",
      "batch": "Weeks 1 to 2",
      "pillar": "Straight Talk",
      "shot": "FACE",
      "length": "28s",
      "onScreenHook": "You don't have a lead problem.",
      "hook": "You don't have a lead problem. You have a follow-up problem. And it's costing you more than any ad ever could.",
      "script": [
        "Every owner I talk to wants more leads. Then I ask what happened to the last thirty people who asked for a quote and didn't book. Nobody knows. Nobody followed up.",
        "The homeowner who requested three quotes hires whoever feels alive first. Most businesses call back in two days. By then it's over.",
        "Before you spend another dollar on ads, go text every person who got a quote from you in the last ninety days. Ask one question: \"Was it price or timing?\"",
        "That's the cheapest sales channel you own and it's just sitting there."
      ],
      "beats": [
        "You don't have a lead problem",
        "You have a FOLLOW-UP problem",
        "What happened to your last 30 quotes?",
        "Text them: 'Was it price or timing?'",
        "Cheapest sales channel you own"
      ],
      "caption": "Before you spend another dollar on ads. Go pull your quotes from the last 90 days that never closed and send one text: \"Hey, was it price or timing?\" Report back what happens, I want to hear it.",
      "ask": null
    },
    {
      "n": 5,
      "title": "What a Voice Agent Actually Sounds Like",
      "batch": "Weeks 1 to 2",
      "pillar": "Under the Hood",
      "shot": "SCREEN",
      "length": "40s",
      "onScreenHook": "This is a real AI answering a real call",
      "hook": "This is not a demo video. I'm calling a voice agent right now and you're going to hear the whole thing.",
      "script": [
        "[Place the call on speaker. Let it play. Do not talk over it.]",
        "[After it books the appointment]",
        "That's it. It answered on the first ring, it knew the hours, it booked the appointment, and it texted the owner the details. It does not take lunch, it does not quit, and it does not get overwhelmed on a Friday.",
        "I'm not telling you to buy one. I'm telling you this is what your customer at 8pm is comparing you to now."
      ],
      "beats": [
        "Real call. Not a demo.",
        "live captions of the AI's actual words",
        "Answered on ring 1",
        "Booked it",
        "Texted the owner"
      ],
      "caption": "No editing, no script, just a real call to a real voice agent. Whatever you think about AI, this is what your after-hours customer is comparing you to now. Curious what you make of it. 👇",
      "ask": "1 of 3 this month"
    },
    {
      "n": 6,
      "title": "The Busier You Get, The More You Lose",
      "batch": "Weeks 1 to 2",
      "pillar": "The Leak",
      "shot": "FACE",
      "length": "30s",
      "onScreenHook": "The busier you get, the more money you lose.",
      "hook": "Here's the trap nobody warns you about. The busier your business gets, the more money you lose.",
      "script": [
        "Think about it. When you're slow, you answer every call on the first ring. When you're slammed, which is exactly when the calls are worth the most, you're on a roof or under a sink or in somebody's chair. The phone rings out.",
        "So your best week is also your leakiest week. Your growth is capped by your own two hands.",
        "Every business that broke past this did the same thing. They stopped requiring themselves to be the one who answers.",
        "That's it. That's the whole ceiling."
      ],
      "beats": [
        "Busier = more money lost",
        "Slow week: answer every call",
        "Best week: phone rings out",
        "Your growth is capped by your two hands",
        "Stop being the one who answers"
      ],
      "caption": "The Main Street trap. Your best week is your leakiest week. Anyone else feel this one? What's your busiest day and what happens to the phone on it?",
      "ask": null
    },
    {
      "n": 7,
      "title": "Your 1-Star Reviews Have a Pattern",
      "batch": "Weeks 1 to 2",
      "pillar": "Steal This",
      "shot": "BOTH",
      "length": "32s",
      "onScreenHook": "Paste your 1-star reviews into AI. Ask this.",
      "hook": "Copy every bad review you've ever gotten, paste them into ChatGPT, and ask it one question.",
      "script": [
        "\"What is the single most common complaint across all of these, and what would fix it?\"",
        "You will get an answer you did not expect. It's almost never the thing you've been defending. It's usually communication. Nobody told them when you'd arrive. Nobody called when you were running late.",
        "You've read those reviews one at a time and felt attacked. Read all forty at once and it stops being personal and starts being a checklist.",
        "Free, takes ten minutes, and it's the most useful thing AI does for a small business that has nothing to do with chatbots."
      ],
      "beats": [
        "Paste ALL your bad reviews into AI",
        "Ask: what's the ONE pattern?",
        "It's almost never what you think",
        "It's usually communication",
        "10 minutes. Free."
      ],
      "caption": "Steal this. It takes ten minutes and it will sting a little. Reading your bad reviews one at a time feels like an attack. Reading forty at once turns it into a checklist. Try it and tell me what your pattern was.",
      "ask": null
    },
    {
      "n": 8,
      "title": "Most Small Business Chatbots Are Worse Than Nothing",
      "batch": "Weeks 1 to 2",
      "pillar": "Straight Talk",
      "shot": "FACE",
      "length": "30s",
      "onScreenHook": "Most small business chatbots are worse than nothing.",
      "hook": "I build AI for small businesses and I'm telling you most of the chatbots on small business websites are worse than having nothing.",
      "script": [
        "Here's why. A bubble pops up, it says \"Hi! How can I help?\" and then it cannot help. It cannot check your calendar, it cannot quote your job, it cannot reach you. It takes an interested customer and gives them a dead end wearing a friendly face.",
        "A plain contact form is more honest. At least it does not promise a conversation it cannot have.",
        "The test for any AI in your business is one question: can it actually complete something? Book the job, take the order, get the message to a human who calls back. If it can only chat, it's decoration.",
        "Decoration does not pay for itself."
      ],
      "beats": [
        "Most SMB chatbots are worse than nothing",
        "'Hi! How can I help?' ...then it can't",
        "A contact form is more honest",
        "THE TEST: can it COMPLETE something?",
        "If it only chats, it's decoration"
      ],
      "caption": "I build this stuff and I'll still say it. If the AI on your site can't book, quote, or reach a human, it's decoration and decoration doesn't pay for itself. Fight me in the comments. 👇",
      "ask": null
    },
    {
      "n": 9,
      "title": "The Speed-to-Lead Clock",
      "batch": "Weeks 3 to 4",
      "pillar": "The Leak",
      "shot": "FACE",
      "length": "27s",
      "onScreenHook": "5 minutes vs 30 minutes. It's not close.",
      "hook": "Calling a new lead in five minutes instead of thirty is not a small improvement. It's a different business.",
      "script": [
        "The person who filled out your form filled out two others. They're sitting there with their phone in their hand, actively deciding. That window is minutes wide, not hours.",
        "Most small businesses call back the next morning. By then the job is sold, the customer is relieved, and you're the guy who called too late.",
        "You do not have to be better. You have to be first. First to respond, first to get paid."
      ],
      "beats": [
        "5 min vs 30 min = a different business",
        "They filled out 2 other forms",
        "The window is MINUTES",
        "You don't have to be better. You have to be FIRST."
      ],
      "caption": "Speed-to-lead is the least sexy and most profitable thing in home services. How fast do you actually call a new lead back? Be honest. 👇",
      "ask": null
    },
    {
      "n": 10,
      "title": "Turn 100 Invoices Into a Price Book",
      "batch": "Weeks 3 to 4",
      "pillar": "Under the Hood",
      "shot": "SCREEN",
      "length": "38s",
      "onScreenHook": "Your last 100 invoices are a business plan.",
      "hook": "Your last hundred invoices are a business plan and you're using them as a filing cabinet.",
      "script": [
        "Export them. Drop them into AI. Ask it three things.",
        "One: what are my ten most common jobs and what did I actually charge for each. Two: which job type takes the most time for the least money. Three: what should my standard price list look like.",
        "Nearly every owner who does this finds the same thing. There's one job they keep saying yes to that quietly loses money, and one they under-charge for that customers never blink at.",
        "You've been guessing at your prices. The answer was in your own paperwork the whole time."
      ],
      "beats": [
        "[screen record an actual spreadsheet + prompt] \"Export your invoices",
        "Ask: my 10 most common jobs + real prices",
        "Which job LOSES money?",
        "There's always one",
        "The answer was in your own paperwork"
      ],
      "caption": "The most valuable AI use case in your business is boring. It's your invoices. Here's the exact prompt on screen. Try it and tell me which job turned out to be the loser, there's always one.",
      "ask": null
    },
    {
      "n": 11,
      "title": "The 9:14pm Booking",
      "batch": "Weeks 3 to 4",
      "pillar": "The Leak",
      "shot": "FACE",
      "length": "28s",
      "onScreenHook": "She tried to book at 9:14pm. You closed at 6.",
      "hook": "Your best client tried to book at 9:14 at night. Your front desk went home at six. She booked somewhere else by 9:16.",
      "script": [
        "This is the part owners get wrong about after-hours. It's not that the customer will call back tomorrow. It's that the decision was happening right then, on the couch, phone in hand, in a two-minute window.",
        "The sale doesn't wait for business hours. It evaporates.",
        "Salons, med spas, dental, anything people book for themselves. Look at when your competitors get booked and you'll find a spike after 8pm. That's your money, and you were asleep.",
        "The most expensive employee is the one who isn't there at 9pm."
      ],
      "beats": [
        "9:14pm",
        "Your desk left at 6",
        "9:16pm: she booked elsewhere",
        "The sale doesn't wait. It evaporates.",
        "The most expensive employee is the one who isn't there at 9pm."
      ],
      "caption": "For anyone in salon, spa, dental, or anything people book for themselves: pull your booking data and look at what happens after 8pm. Then look at what happens to the phone. That gap is the whole post.",
      "ask": null
    },
    {
      "n": 12,
      "title": "Your Best Salesperson Is a Script",
      "batch": "Weeks 3 to 4",
      "pillar": "Steal This",
      "shot": "BOTH",
      "length": "35s",
      "onScreenHook": "Record your best closer. Steal their brain.",
      "hook": "Whoever is best on the phone at your company, record three of their calls this week. With their permission. Then do this.",
      "script": [
        "Drop the transcripts into AI and ask: what exactly does this person do that the others don't. What order do they ask questions in. Where do they handle the price objection. What's the exact line they use to book.",
        "You'll get a one-page script. That's not a manager's guess about what good looks like. That's what your actual best person actually does, written down.",
        "Hand it to everyone else. That's the cheapest training you will ever run, and it beats any sales course because it's already working in your business.",
        "Costs nothing. Do it this week."
      ],
      "beats": [
        "Record your best closer, 3 calls",
        "Transcripts",
        "AI",
        "What do THEY do that others don't?",
        "You now have a real script",
        "Cheapest training you'll ever run"
      ],
      "caption": "Free move. Your best salesperson already solved this and nobody wrote it down. Three calls, one prompt, one page. Who's your best phone person and what do they do that nobody else does?",
      "ask": null
    },
    {
      "n": 13,
      "title": "The Question You Answer 40 Times a Week",
      "batch": "Weeks 3 to 4",
      "pillar": "The Leak",
      "shot": "FACE",
      "length": "30s",
      "onScreenHook": "You answer the same 8 questions all week.",
      "hook": "There are about eight questions you answer every single week, over and over, and they're eating hours you never billed for.",
      "script": [
        "Do you service my area. How much is a basic one. Are you licensed. When can you come out. Do you take card. Can you do it Saturday.",
        "Scroll back through your last fifty customer texts and count them. Same eight.",
        "Two moves. Put the answers on your website in plain language, not buried in a PDF. And put them where the phone can reach them, so anything answering after hours can handle it without you.",
        "You are being paid nothing to be your own FAQ page."
      ],
      "beats": [
        "The same 8 questions. Every week.",
        "Do you service my area? / How much? / Can you come Saturday?",
        "Scroll back 50 texts and count",
        "You're being paid NOTHING to be your own FAQ"
      ],
      "caption": "Go scroll back through your last 50 customer texts and count how many are the same eight questions. Post your number below, I want to see how bad this is across industries.",
      "ask": null
    },
    {
      "n": 14,
      "title": "Photo to Estimate",
      "batch": "Weeks 3 to 4",
      "pillar": "Under the Hood",
      "shot": "SCREEN",
      "length": "33s",
      "onScreenHook": "They send a photo. You send a ballpark. In 60 seconds.",
      "hook": "Customer texts you a photo of the problem. Instead of driving out there for a free estimate you may not win, do this.",
      "script": [
        "[Screen: drop a photo into AI with a real prompt]",
        "Give AI the photo, your price book, and this instruction: \"Based on this photo and my standard pricing, draft a ballpark range and the three questions I need answered before I can be exact.\"",
        "You get a range and the qualifying questions in under a minute. You send it. Now you know if this person is real before you burn a two-hour round trip on a tire-kicker.",
        "You're still the one who prices it. AI just stopped you from driving across the county for free."
      ],
      "beats": [
        "[real screen recording] \"Photo + your price book + this prompt",
        "Ballpark range in 60s",
        "Plus the 3 questions you still need",
        "Stop driving 2 hours for tire-kickers"
      ],
      "caption": "Exact prompt on screen. This one's for anyone who's ever driven 45 minutes to a free estimate for someone who was never going to book. You still set the price. This just filters.",
      "ask": null
    },
    {
      "n": 15,
      "title": "AI Won't Fix a Business That Doesn't Answer",
      "batch": "Weeks 3 to 4",
      "pillar": "Straight Talk",
      "shot": "FACE",
      "length": "26s",
      "onScreenHook": "AI won't save a business that doesn't answer the phone.",
      "hook": "I sell AI to small businesses and here's what I tell people who want to buy it for the wrong reason.",
      "script": [
        "AI will not fix a business that doesn't answer the phone. It will just help you miss calls faster and more professionally.",
        "If your problem is that you never call people back, that's a habit, and no software fixes a habit. If your problem is that you physically cannot be in two places at once, that's capacity, and that's what this stuff is actually for.",
        "Be honest with yourself about which one you have. One of them costs money to solve. The other one costs discipline, and it's free."
      ],
      "beats": [
        "AI won't fix a business that doesn't answer",
        "It'll help you miss calls FASTER",
        "Habit problem? No software fixes that.",
        "Capacity problem? That's what it's for.",
        "One costs money. One costs discipline."
      ],
      "caption": "The honest version from someone who sells this stuff. Half the people who ask me about AI have a discipline problem, not a capacity problem, and I'd rather say it than take the money. Which one is yours?",
      "ask": null
    },
    {
      "n": 16,
      "title": "Reply to Every Review, Automatically",
      "batch": "Weeks 3 to 4",
      "pillar": "Steal This",
      "shot": "SCREEN",
      "length": "30s",
      "onScreenHook": "Unreplied reviews are costing you ranking.",
      "hook": "Every review you never replied to is quietly costing you position in local search.",
      "script": [
        "Google says it plainly. Responding to reviews affects local ranking. Most small businesses reply to none of them, or only the angry ones, which is the worst possible pattern.",
        "Here's the free version. Once a week, pull your new reviews, drop them into AI, and ask for a short warm reply to each one that mentions the specific thing they said. Read them, fix anything that sounds like a robot, paste them in.",
        "Fifteen minutes a week. It moves your ranking and it makes the next person reading those reviews trust you more."
      ],
      "beats": [
        "[screen: reviews",
        "prompt",
        "drafted replies] \"Google: replying affects local ranking",
        "Most businesses reply to NONE",
        "Weekly: reviews",
        "AI",
        "warm replies",
        "READ THEM FIRST",
        "15 min/week"
      ],
      "caption": "Free and it takes fifteen minutes a week. One rule: actually read them before you post. A reply that sounds like a robot is worse than no reply and people can tell instantly.",
      "ask": null
    },
    {
      "n": 17,
      "title": "The Dead Lead Goldmine",
      "batch": "Weeks 5 to 6",
      "pillar": "Steal This",
      "shot": "FACE",
      "length": "30s",
      "onScreenHook": "There's $20k sitting in your old quotes.",
      "hook": "There is money sitting in your file of old quotes that never closed and you have never once gone back for it.",
      "script": [
        "Pull every quote from the last twelve months that never turned into a job. Send one text. Not a sales pitch. This:",
        "\"Hey, it's Sarah at [business]. We quoted you back in March. Just checking, did you ever get that handled?\"",
        "That's it. No offer, no discount, no pressure. A real number of them never did get it handled. Life happened, they meant to call you back, they forgot.",
        "The people who already trusted you enough to ask for a price are the warmest list you will ever have and it's free."
      ],
      "beats": [
        "Your old quotes = money",
        "Pull 12 months of dead quotes",
        "'Did you ever get that handled?'",
        "No pitch. No discount.",
        "Warmest list you'll ever own"
      ],
      "caption": "Do this on a slow afternoon. One text, no pitch, no discount, just \"did you ever get that handled?\" Come back and tell me what it turned up. This one surprises people.",
      "ask": null
    },
    {
      "n": 18,
      "title": "Your Website's 3-Second Problem",
      "batch": "Weeks 5 to 6",
      "pillar": "Under the Hood",
      "shot": "SCREEN",
      "length": "32s",
      "onScreenHook": "Test your site on cell service, not wifi.",
      "hook": "Pull up your website on your phone right now, on cell service, not wifi. Count the seconds.",
      "script": [
        "[Screen record the actual load, count on screen]",
        "More than three and you're losing a large share of the people who tapped. They don't wait. They go back and tap the next result, and you paid for that click.",
        "It's almost always the same culprit: giant photos nobody compressed. Your web person uploaded the raw camera files.",
        "Run your URL through Google PageSpeed Insights. It's free, it takes thirty seconds, and it hands you the actual list. Send that list to whoever built your site.",
        "You do not have to understand it. You just have to make somebody fix it."
      ],
      "beats": [
        "[real timed load] \"On CELL service, not wifi",
        "3+ seconds = you're losing them",
        "It's always the photos",
        "PageSpeed Insights, free, 30 seconds",
        "You don't have to understand it. Just make someone fix it."
      ],
      "caption": "Test it on cell service, not your office wifi. That's the difference between what you see and what your customer sees. Drop your load time below and I'll tell you if it's a problem.",
      "ask": null
    },
    {
      "n": 19,
      "title": "The Sunday Paperwork Tax",
      "batch": "Weeks 5 to 6",
      "pillar": "The Leak",
      "shot": "FACE",
      "length": "28s",
      "onScreenHook": "You didn't start a business to work Sundays.",
      "hook": "If you spend Sunday doing paperwork, you don't own a business. You bought yourself a second job with worse hours.",
      "script": [
        "Invoices, quotes, scheduling, the texts you didn't answer. It piles up all week and it lands on the one day you were supposed to have.",
        "Here's the thing about that pile. Almost none of it requires your judgment. It requires your attention. Those are different, and only one of them has to be you.",
        "Pick the single biggest item on your Sunday list and ask one question: does this need me, or does it just need someone.",
        "Start there. Not with AI, not with software. With that question."
      ],
      "beats": [
        "Sunday paperwork = a second job",
        "It piles up all week",
        "Does it need your JUDGMENT or your ATTENTION?",
        "Only one has to be you",
        "Start with the question, not the software"
      ],
      "caption": "For every owner who's reading this on a Sunday with a stack of invoices next to them. What's the one thing on your Sunday list you'd hand off first? 👇",
      "ask": null
    },
    {
      "n": 20,
      "title": "Write the Job Post That Filters",
      "batch": "Weeks 5 to 6",
      "pillar": "Steal This",
      "shot": "BOTH",
      "length": "32s",
      "onScreenHook": "Bad applicants are a job-post problem.",
      "hook": "If you're drowning in unqualified applicants, that's not a labor market problem. That's a job post problem.",
      "script": [
        "Take your current job post, drop it in AI, and ask: \"Rewrite this so the wrong people screen themselves out. Be specific about the hard parts, the schedule, and the pay range.\"",
        "Most job posts are written to attract everyone. That's the mistake. A good one repels. It says the truck leaves at 6:15am, you'll be in an attic in August, here's the actual number.",
        "You'll get fewer applications and better ones, and you'll stop spending your week interviewing people who were never going to take it.",
        "Say the hard part out loud. The right person reads it and thinks \"finally, someone honest.\""
      ],
      "beats": [
        "Bad applicants = bad job post",
        "Most posts attract EVERYONE",
        "A good one REPELS",
        "Truck leaves at 6:15am. Attic in August. Here's the pay.",
        "Fewer applications. Better ones."
      ],
      "caption": "Hiring is brutal right now and most of it is self-inflicted. Say the hard part out loud in the post. What's the one thing about your job you'd warn someone about? That's your first line.",
      "ask": null
    },
    {
      "n": 21,
      "title": "The Competitor Phone Test",
      "batch": "Weeks 5 to 6",
      "pillar": "The Leak",
      "shot": "FACE",
      "length": "30s",
      "onScreenHook": "Call your 3 biggest competitors. After hours.",
      "hook": "Call your three biggest competitors tonight, after hours, as a customer. This is the most useful twenty minutes you'll spend this month.",
      "script": [
        "You're finding out one thing: who answers.",
        "Usually it's nobody. Sometimes it's one of them, and that one is quietly eating everybody's after-hours work and nobody in your market has figured out why they're growing.",
        "Then remember that your customers run this exact test on you. Every single evening. They just call down the list until somebody picks up.",
        "Whoever answers wins. That's not strategy, that's just arithmetic."
      ],
      "beats": [
        "Call your 3 competitors. Tonight.",
        "You're finding out ONE thing: who answers",
        "Usually nobody. Sometimes one.",
        "That one is eating the market.",
        "Your customers run this test on YOU. Every night."
      ],
      "caption": "Twenty minutes tonight. Call your three biggest competitors after hours and just listen. Report back what you find, I'm genuinely curious how many actually pick up in your industry.",
      "ask": null
    },
    {
      "n": 22,
      "title": "One Job, Ten Pieces of Content",
      "batch": "Weeks 5 to 6",
      "pillar": "Steal This",
      "shot": "SCREEN",
      "length": "35s",
      "onScreenHook": "One jobsite photo = 10 posts.",
      "hook": "You take before-and-after photos on every job and then do nothing with them. Here's the fix, and it takes four minutes.",
      "script": [
        "[Screen: photo + prompt]",
        "Drop the photo in and say: \"I'm a [trade]. Write me a short Facebook post about this job for local homeowners. No hashtags, no hype, write like a person. Then give me three variations.\"",
        "Now you have a week of posts from one job you already did.",
        "The reason this works is that people do not hire you because you posted a tip. They hire you because they saw you actually doing the work, over and over, until you were the obvious person to call.",
        "Consistency beats cleverness. The photo is already on your phone."
      ],
      "beats": [
        "[real prompt on screen] \"You already take the photos",
        "Photo + 'write like a person, no hashtags'",
        "1 job = a week of posts",
        "People hire you because they SAW you working",
        "Consistency > cleverness"
      ],
      "caption": "Exact prompt on screen. The photos are already on your phone from jobs you already did. This is the lowest-effort marketing in the trades and almost nobody runs it.",
      "ask": null
    },
    {
      "n": 23,
      "title": "Stop Asking AI to Write Your Marketing",
      "batch": "Weeks 5 to 6",
      "pillar": "Straight Talk",
      "shot": "FACE",
      "length": "27s",
      "onScreenHook": "Stop asking AI to write your marketing.",
      "hook": "Stop asking AI to write your marketing. It's the worst thing you can use it for and it's the first thing everyone tries.",
      "script": [
        "Everybody's feed is full of the same beige AI paragraphs now and customers can smell it. You are not going to out-content the internet.",
        "Point it at the stuff nobody sees instead. Your invoices. Your calendar. Your missed calls. Your bad reviews. Your quote follow-ups.",
        "That's where the money is, and it's boring, which is exactly why nobody's doing it.",
        "The best AI use case in your business is not a clever caption. It's the fact that nobody called Mrs. Henderson back."
      ],
      "beats": [
        "Stop using AI for marketing",
        "Everyone's feed is beige now. Customers can smell it.",
        "Point it at: invoices / calendar / missed calls / bad reviews",
        "Boring is where the money is",
        "Nobody called Mrs. Henderson back."
      ],
      "caption": "Hot take from someone who builds AI for small businesses. The good use cases are boring and that's exactly why they're still available. What's the most boring thing in your week? That's probably the answer.",
      "ask": null
    },
    {
      "n": 24,
      "title": "What I'd Do With Your First 30 Days",
      "batch": "Weeks 5 to 6",
      "pillar": "Under the Hood",
      "shot": "FACE",
      "length": "40s",
      "onScreenHook": "If you gave me your business for 30 days.",
      "hook": "If you handed me your small business for thirty days and told me to find money without spending any, here is exactly what I'd do, in order.",
      "script": [
        "Week one, I'd find out how many calls you miss. Just the number. Most owners have never seen it and it's the most upsetting number in the business.",
        "Week two, I'd turn on missed-call text-back and fix your review link. Both free, both take an afternoon.",
        "Week three, I'd text every dead quote from the last year with one question: did you ever get that handled.",
        "Week four, I'd read all your bad reviews at once and fix the one thing they all say.",
        "Zero dollars. Four afternoons. That's the whole list, and it's more than most businesses do in a year."
      ],
      "beats": [
        "30 days. No budget.",
        "WK 1: count your missed calls",
        "WK 2: text-back + review link",
        "WK 3: text your dead quotes",
        "WK 4: read all your bad reviews at once",
        "$0. Four afternoons."
      ],
      "caption": "Save this one. Four weeks, zero dollars, four afternoons, and it's more than most businesses do in a year. I do this every week for free in the group, link in the comments. Start with week one and tell me your missed-call number, I promise it's worse than you think.",
      "ask": "2 of 3 this month"
    }
  ],
  "posts": [
    {
      "id": "fb-01",
      "pillar": "Thesis",
      "headline": "Big companies got AI first. That's backwards.",
      "fb": [
        "Big companies got AI first. That's backwards.",
        "It isn't the Fortune 500 that loses a $4,000 job because nobody picked up at 5:15 on a Friday. It's the plumber. The salon. The family restaurant that had two people on and forty phone calls.",
        "Main Street feels every dropped call in its bank account the same week it happens. And Main Street is the one place that got handed AI last, in the form of a chatbot bubble that can't do anything.",
        "So I started posting here. Every week I'm going to give away the specific moves that put money back in a small business. Free, no course, no funnel. Some of them involve AI. Half of them are just a switch you already pay for and never turned on.",
        "Tell me what you do in the comments and I'll tell you where I'd start."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-07-27",
      "dateLabel": "Mon, Jul 27"
    },
    {
      "id": "fb-02",
      "pillar": "Ritual",
      "headline": "Comment your industry. I'll give you the one AI move that pays for itself.",
      "fb": [
        "Comment your industry below and I'll give you the one AI move I'd make first in your specific business. Free, no pitch, I'm not going to DM you.",
        "Not \"use AI to save time.\" An actual move. The thing I'd do on Monday morning if it were my company.",
        "Roofing is different from a med spa. A two-truck landscaping outfit is different from a twelve-chair salon. Generic advice is why most owners have concluded this stuff isn't for them.",
        "So tell me: what do you do, how many people, and what's the part of the week that makes you want to quit?",
        "I answer every one of these. Might take me a day, but I get to all of them."
      ],
      "firstComment": "Everything I post here goes deeper in the free group: {{GROUP_URL}}. No pitching, no spam, just the moves that put money back in a small business.",
      "cta": false,
      "date": "2026-07-30",
      "dateLabel": "Thu, Jul 30"
    },
    {
      "id": "fb-03",
      "pillar": "Steal This",
      "headline": "Five fields on your Google profile that almost nobody fills in.",
      "fb": [
        "Your Google Business Profile is the most valuable piece of real estate you own and most owners set it up once in 2021 and never touched it again.",
        "Five things to fix this afternoon. All free, all take about twenty minutes together.",
        "1. Services. Not just \"plumber.\" List every specific job you do, in the words customers use. Water heater replacement. Slab leak. Garbage disposal. Each one is a search someone is typing right now.",
        "2. Photos. Yours are three years old and there are four of them. Add ten from recent jobs. Profiles with fresh photos get meaningfully more calls, and it's the cheapest thing on this list.",
        "3. Hours, including holidays. Wrong hours generate one-star reviews from people who drove out to a closed door.",
        "4. The Q&A section. You can ask and answer your own questions. Nobody knows this. Put your eight most common questions in there yourself.",
        "5. Products or services with prices, even ranges. \"Starting at\" is fine. People filter you out for not saying anything far more often than for saying a number.",
        "Which of the five is worst on yours? Be honest, mine was the photos for years."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-01",
      "dateLabel": "Sat, Aug 1"
    },
    {
      "id": "fb-04",
      "pillar": "The Leak",
      "headline": "\"We'll get back to you\" is where most small business revenue goes to die.",
      "fb": [
        "\"We'll get back to you.\" That sentence is where most small business revenue quietly goes to die.",
        "Not because anyone lied. Because the person who said it went to the next job, and the note was on a scrap of paper in a truck, and it's Thursday now.",
        "Here's the three-text sequence that fixes it. Steal it, it costs nothing.",
        "Text 1, same day: \"Hey [name], Sarah from [business]. Great talking with you. Sending the quote over tonight.\" (Send it that night. This is the whole trick.)",
        "Text 2, day 3: \"Just making sure that quote landed, any questions on it?\"",
        "Text 3, day 8: \"No pressure at all, just closing the loop. Was it price or timing? Genuinely helps me either way.\"",
        "That last one is the one people skip and it's the most valuable. Half of them answer it honestly, and now you know something real about your pricing that no consultant could tell you.",
        "How many days go by before you follow up on a quote right now? Nobody's judging, I want to see the real spread."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-03",
      "dateLabel": "Mon, Aug 3"
    },
    {
      "id": "fb-05",
      "pillar": "Straight Talk",
      "headline": "Four things AI genuinely cannot do for your business.",
      "fb": [
        "I build AI for small businesses, so here are four things it genuinely cannot do. Anyone telling you otherwise is selling.",
        "1. It cannot make a judgment call about a customer. Whether to eat the cost on a job that went sideways, whether this person is worth keeping. That's you. That will stay you.",
        "2. It cannot fix a business that doesn't answer the phone. If the problem is a habit, software just helps you miss things faster and more professionally.",
        "3. It cannot know your prices, your area, or your standards unless somebody sits down and tells it. The setup is real work. Anyone promising \"plug it in, done\" has never done it.",
        "4. It cannot replace being the person people trust. In a small business the owner IS the brand. Automating the parts nobody sees is smart. Automating the relationship is how you lose it.",
        "What it's actually good at is the boring middle. The calls at 8pm. The follow-up nobody sent. The paperwork on Sunday. The eight questions you answer forty times a week.",
        "That's not a sexy pitch, but it's the honest one.",
        "What's the thing you'd never hand to a machine, no matter how good it got?"
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-06",
      "dateLabel": "Thu, Aug 6"
    },
    {
      "id": "fb-06",
      "pillar": "Ritual",
      "headline": "Teardown Tuesday. Drop your business. I'll find the leak on video. Free.",
      "fb": [
        "TEARDOWN TUESDAY. Here's how it works.",
        "Drop your business name and website in the comments. I pick one. Then I pull up your site, your Google profile, and I call your business on camera, live, as a customer.",
        "Then I tell you exactly where you're losing money and the one thing I'd fix first. On video, free, and you keep the video.",
        "Two promises. I will never mock anybody, we're on the same side against the problem. And I always give you the free version of the fix, even when there's a paid version.",
        "Only volunteers. I don't do this to businesses that didn't raise their hand.",
        "Who wants it? First good one I see, I shoot it tonight."
      ],
      "firstComment": "Everything I post here goes deeper in the free group: {{GROUP_URL}}. No pitching, no spam, just the moves that put money back in a small business.",
      "cta": false,
      "date": "2026-08-08",
      "dateLabel": "Sat, Aug 8"
    },
    {
      "id": "fb-07",
      "pillar": "The Leak",
      "headline": "Your voicemail greeting was recorded by an employee who quit two years ago.",
      "fb": [
        "Go listen to your own voicemail greeting right now. I'll wait.",
        "Here's what I hear when I call small businesses all day. A greeting recorded by somebody who doesn't work there anymore. Hours that are wrong. A mailbox that's full. A robot voice reading back a phone number because nobody ever recorded anything at all.",
        "Meanwhile the person calling is standing in a flooded kitchen at 6pm deciding who to give four thousand dollars to.",
        "Fix it in ten minutes, free:",
        "Record it yourself, in your voice. Say the business name, say you're sorry you missed them, and then say this: \"Text this same number and we'll get right back to you.\"",
        "Then actually watch your texts.",
        "People who would never leave a voicemail will happily send a text. You just recovered a chunk of the work you were losing, before lunch, for nothing.",
        "Go listen to yours and tell me how bad it is. I want to hear the worst one."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-10",
      "dateLabel": "Mon, Aug 10"
    },
    {
      "id": "fb-08",
      "pillar": "Steal This",
      "headline": "Paste your last 50 customer texts into AI and ask it this one question.",
      "fb": [
        "Prompt of the week. Copy this exactly.",
        "Scroll back through your last fifty customer texts. Copy them, paste them into ChatGPT or Claude, and say:",
        "\"These are real messages from my customers. Find the questions I answer most often, ranked. For each one, write the answer in plain language a customer would understand, in my voice based on how I already replied.\"",
        "What you get back is your FAQ page, written for you, in words your actual customers actually use. Not marketing words. Their words.",
        "Put those answers on your website. Put them in your voicemail greeting. Put them anywhere someone can reach them at 9pm without you.",
        "Right now you are being paid nothing to personally be your own FAQ page, forty times a week, usually while driving.",
        "Run it and tell me your number one question. I'm collecting these by industry and the pattern is fascinating."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-13",
      "dateLabel": "Thu, Aug 13"
    },
    {
      "id": "fb-09",
      "pillar": "Straight Talk",
      "headline": "\"You're too expensive\" almost never means you're too expensive.",
      "fb": [
        "\"You're too expensive\" almost never means you're too expensive.",
        "It usually means one of three other things, and they all have a different fix.",
        "\"I don't understand what I'm getting.\" Your quote was a number on a line. The guy who won showed them what's included and why the cheap version fails in two years.",
        "\"I don't trust that you'll show up.\" Price is the only thing they can compare, so they compare it. Reviews, photos, and answering the phone fix this one, not discounting.",
        "\"I wasn't ready to buy today.\" Nothing was wrong with your price. They needed two more weeks and you never followed up, so they bought from whoever was still around when they were ready.",
        "Almost nobody's real problem is the number. Dropping your price to solve a trust problem just makes you a cheaper business with the same trust problem.",
        "What's the objection you hear most? I'll tell you which of the three it actually is."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-15",
      "dateLabel": "Sat, Aug 15"
    },
    {
      "id": "fb-10",
      "pillar": "The Leak",
      "headline": "The contractor who calls back first wins the job most of the time.",
      "fb": [
        "The one who calls back first wins the job most of the time. Not the best one. The first one.",
        "Here's what people get wrong about this. They think the customer is comparing three quotes carefully over a week. They're not. They filled out three forms in four minutes, they're sitting there with the phone in their hand, and they are actively deciding right now.",
        "That window is minutes wide.",
        "Most small businesses call back the next morning. By then somebody else already came out, quoted it, and the customer is relieved it's handled.",
        "You do not have to be better than your competition. You have to be awake at the same time as your customer.",
        "Honest question, no judgment: how long does it actually take you to call a new lead back? Not how long you'd like it to take. The real number."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-17",
      "dateLabel": "Mon, Aug 17"
    },
    {
      "id": "fb-11",
      "pillar": "Ritual",
      "headline": "Win Friday. What worked this week? Big or stupidly small.",
      "fb": [
        "WIN FRIDAY. What worked this week?",
        "Doesn't have to be big. Especially shouldn't be big. Post the small one.",
        "You finally fixed your review link. You texted an old quote and it turned into a job. You said no to a customer who was going to be a nightmare. You got out of the shop before six once.",
        "I'll go first: I called eleven businesses this week for a teardown and two of them answered. Two out of eleven. Every time I run this I'm reminded the bar on Main Street is on the floor, and that's genuinely good news for anyone willing to just pick up the phone.",
        "Your turn. What went right? 👇"
      ],
      "firstComment": "Everything I post here goes deeper in the free group: {{GROUP_URL}}. No pitching, no spam, just the moves that put money back in a small business.",
      "cta": false,
      "date": "2026-08-20",
      "dateLabel": "Thu, Aug 20"
    },
    {
      "id": "fb-12",
      "pillar": "Steal This",
      "headline": "Export last month's calendar into AI and ask where your week actually went.",
      "fb": [
        "Export last month's calendar to a spreadsheet, drop it into AI, and ask this:",
        "\"Categorize every entry as revenue-generating, admin, or travel. Show me the hours and percentage in each. Then tell me what a normal week actually looks like for me.\"",
        "Almost every owner who runs this finds the same two things. Way more travel than they thought, and one recurring meeting or errand that eats half a day a week and generates nothing.",
        "You cannot fix a week you've never actually looked at. You've been running on a feeling about where your time goes, and the feeling is wrong in a specific direction: you think you spend more time making money than you do.",
        "Takes fifteen minutes. Free. It's the most uncomfortable and most useful thing on this list.",
        "If you run it, come back and post your percentage. I want to see the spread across industries."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-22",
      "dateLabel": "Sat, Aug 22"
    },
    {
      "id": "fb-13",
      "pillar": "The Leak",
      "headline": "A restaurant's phone rings 40 times on a Friday. Nobody can pick up.",
      "fb": [
        "A busy restaurant's phone rings forty times on a Friday night and almost nobody picks up. Not from laziness. Because the phone and the floor need the same two hands, and the people in front of you are the ones who are already here.",
        "Every one of those rings was a reservation, a to-go order, or a catering lead. Catering is the one that hurts. That's a four-figure call and it went to whoever answered.",
        "You cannot hire your way out of a Friday rush. Nobody's staffing an extra body just to sit by a phone.",
        "The free version: put your reservation link and your online ordering link everywhere the phone is listed, and change your greeting so it tells people that in the first six seconds instead of after a menu tree.",
        "Restaurant folks, what's the call you hate missing most? I'm guessing catering.",
        "🍽️"
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-24",
      "dateLabel": "Mon, Aug 24"
    },
    {
      "id": "fb-14",
      "pillar": "Straight Talk",
      "headline": "Stop asking AI to write your marketing. Point it at your invoices.",
      "fb": [
        "Stop asking AI to write your marketing. It's the first thing everybody tries and it's the worst thing it does for you.",
        "Everyone's feed is full of the same beige AI paragraphs now and customers can smell it from across the room. You are not going to out-post the internet, and honestly nobody hired a plumber because of a caption.",
        "Point it at the stuff nobody sees.",
        "Your invoices, to find the job type that quietly loses money. Your calendar, to find where the week actually goes. Your missed calls, to find out what a Tuesday costs you. Your bad reviews, all at once, to find the one pattern. Your old quotes, to find the money already sitting there.",
        "That's where it earns. It's boring, which is exactly why it's still available.",
        "The best AI use case in your business isn't a clever post. It's the fact that nobody called Mrs. Henderson back.",
        "Disagree with me. I want to hear it."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-27",
      "dateLabel": "Thu, Aug 27"
    },
    {
      "id": "fb-15",
      "pillar": "Steal This",
      "headline": "Google says replying to reviews affects your ranking. Most owners reply to none.",
      "fb": [
        "Google says plainly that responding to reviews affects your local ranking. Most small businesses reply to none of them, or only the angry ones, which is the worst possible pattern to show a stranger reading your profile.",
        "Fifteen minutes a week, free:",
        "Pull the week's new reviews. Drop them into AI and ask for a short, warm, specific reply to each one that mentions the actual thing they said. Then read every single one before you post it and fix anything that sounds like a machine.",
        "That last part is not optional. A reply that reads like a robot is worse than no reply, and people can tell instantly. \"Thank you for your valuable feedback\" makes you look like a cable company.",
        "For the bad ones: acknowledge, don't argue, and take it to a phone call. Anyone reading it later is judging how you handled it, not who was right.",
        "How many reviews are sitting on your profile right now with no reply? Go look. It's usually more than you'd guess."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-29",
      "dateLabel": "Sat, Aug 29"
    },
    {
      "id": "fb-16",
      "pillar": "The Leak",
      "headline": "\"I'll just do it myself\" is the most expensive sentence in small business.",
      "fb": [
        "\"I'll just do it myself, it's faster\" is the most expensive sentence in small business, and every good operator says it.",
        "It's true, by the way. It IS faster this one time. That's what makes it so hard to stop.",
        "But here's the arithmetic. If your work is worth $95 an hour and you spend six hours a week on scheduling, invoicing, and answering the same questions, that's roughly $570 a week you paid yourself to do $18-an-hour work. Call it $27,000 a year.",
        "You wouldn't hire someone at your rate to do that job. But you hired you.",
        "The move isn't to hire a person. For most of you it's not the right time and you know it. The move is to ask one question about every task on that list: does this need my judgment, or does it just need my attention?",
        "Judgment stays. Attention goes.",
        "What's the one thing you keep doing yourself that you know you shouldn't? 👇"
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-08-31",
      "dateLabel": "Mon, Aug 31"
    },
    {
      "id": "fb-17",
      "pillar": "Ritual",
      "headline": "Tell me the worst part of your week. I'll tell you if it's fixable.",
      "fb": [
        "New version of the Monday question. Tell me the worst part of your week and I'll tell you honestly whether it's fixable, and how.",
        "Not \"what would you automate.\" Most owners don't know, and that question makes people feel like they should already have an answer.",
        "Just tell me the thing you dread. The Sunday invoicing. The scheduling phone tag. The one customer. The quotes you never send. The part where you get home and remember four people you didn't call back.",
        "I'll give you a straight answer, including \"that one's not a software problem\" when that's the truth, which is more often than people expect.",
        "Free, no DM, no pitch. I just find these conversations more useful than anything I could write on my own.",
        "Go. 👇"
      ],
      "firstComment": "Everything I post here goes deeper in the free group: {{GROUP_URL}}. No pitching, no spam, just the moves that put money back in a small business.",
      "cta": false,
      "date": "2026-09-03",
      "dateLabel": "Thu, Sep 3"
    },
    {
      "id": "fb-18",
      "pillar": "Steal This",
      "headline": "Drowning in bad applicants is a job-post problem, not a labor problem.",
      "fb": [
        "If you're drowning in unqualified applicants, that's not the labor market. That's your job post.",
        "Take your current one, paste it into AI, and say: \"Rewrite this so the wrong people screen themselves out. Be specific and honest about the hard parts, the schedule, and the pay range.\"",
        "Most job posts are written to attract everybody. That's the whole mistake. A good job post repels.",
        "It says the truck leaves at 6:15, you will be in an attic in August, we drug test, here is the actual number, and here is what you'll be making in two years if you're good.",
        "You'll get fewer applications and better ones, and you'll stop burning a week interviewing people who were never going to take it.",
        "Say the hard part out loud. The right person reads it and thinks \"finally, somebody honest.\"",
        "What's the thing about your job you'd warn someone about? That's your opening line."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-09-05",
      "dateLabel": "Sat, Sep 5"
    },
    {
      "id": "fb-19",
      "pillar": "The Leak",
      "headline": "She tried to book at 9:14pm. Your desk left at 6. She booked elsewhere by 9:16.",
      "fb": [
        "Your best client tried to book at 9:14 at night. Your front desk went home at six. She booked somewhere else at 9:16.",
        "This is the part that owners in booking businesses get wrong about after-hours. It's not that she'll call back tomorrow. It's that the decision was happening right then, on the couch, phone in hand, in a two-minute window that opened because she finally had a second to herself.",
        "The sale doesn't wait for business hours. It evaporates.",
        "Salons, spas, dental, anything people book for themselves: pull your booking data and look at when requests actually come in. There's a spike after 8pm and it's bigger than you think. Then look at what your phone does during that spike.",
        "The free move: make sure online booking is one tap from your Instagram bio, your Google profile, and your voicemail greeting. Not buried on a website. One tap.",
        "The most expensive employee is the one who isn't there at 9pm."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-09-07",
      "dateLabel": "Mon, Sep 7"
    },
    {
      "id": "fb-20",
      "pillar": "Under the Hood",
      "headline": "This is what an AI answering your phone actually sounds like now.",
      "fb": [
        "Whatever picture you have in your head of \"AI answering the phone,\" it's probably four years out of date. It's not the press-1-for-billing tree.",
        "It picks up on the first ring, it knows your hours and your service area, it answers the eight questions you get all week, it books straight into your calendar, and it texts you the details before you're off the ladder.",
        "I'm not posting this to sell you one. I'm posting it because this is what your customer at 8pm is comparing you to now, whether you like it or not. Somebody in your market already has this and is quietly eating the after-hours work.",
        "You can call one and hear it yourself. Link in the comments, free, no signup, it just rings your phone and talks to you.",
        "Then tell me honestly what you thought. I want the skeptical takes too, they're usually the most useful ones."
      ],
      "firstComment": "You can call one and hear it: modernmustardseed.com/voice-agents/forge. Free, no signup, it just calls you.",
      "cta": true,
      "date": "2026-09-10",
      "dateLabel": "Thu, Sep 10"
    },
    {
      "id": "fb-21",
      "pillar": "Steal This",
      "headline": "There's money sitting in your old quotes and you've never gone back for it.",
      "fb": [
        "Slow afternoon project that costs nothing and works almost every time.",
        "Pull every quote from the last twelve months that never turned into a job. Send one text. Not a pitch:",
        "\"Hey, it's Sarah at [business]. We quoted you back in March for the deck. Just checking in, did you ever get that handled?\"",
        "No offer. No discount. No pressure. Just a human closing a loop.",
        "A real number of them never did get it handled. Life happened, they meant to call you back, they got busy, and now they feel a little bad about it and you just made it easy.",
        "These people already trusted you enough to invite you out and ask what it would cost. That is the warmest list you will ever own, it's free, and it's sitting in a folder.",
        "Try it on twenty of them this week and come back and tell me what happened. This one surprises people every time."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-09-12",
      "dateLabel": "Sat, Sep 12"
    },
    {
      "id": "fb-22",
      "pillar": "Straight Talk",
      "headline": "Your customers stopped answering the phone. They didn't stop wanting to buy.",
      "fb": [
        "Your customers stopped answering unknown numbers. They did not stop wanting to hire you.",
        "This trips up a lot of good operators. You call back, no answer, you leave a voicemail, nothing, and you conclude the lead was junk. It wasn't. They just don't answer numbers they don't recognize, and neither do you.",
        "The fix is boring: call, and if there's no answer, immediately text. \"Hey [name], Sarah from [business], just tried you about the water heater. Happy to text if that's easier.\"",
        "Response rates on that second step are not close. People who ignored the call will reply to the text in four minutes.",
        "And when they text back, keep texting. Don't insist on getting them on the phone because that's how you prefer to sell. Sell the way they want to buy.",
        "Anyone else notice their phone answer rate falling off a cliff the last few years? What are you doing about it?"
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-09-14",
      "dateLabel": "Mon, Sep 14"
    },
    {
      "id": "fb-23",
      "pillar": "The Leak",
      "headline": "Load your site on cell service, not office wifi. Count the seconds.",
      "fb": [
        "Pull up your own website on your phone right now, on cell service, not your office wifi. Count the seconds until you can actually read something.",
        "More than three and you're losing a real share of the people who tapped. They don't wait. They hit back and tap the next result, and if that tap came from an ad, you paid for it.",
        "It's almost always the same cause. Enormous photos nobody compressed. Somebody uploaded the raw files straight off a camera and every visitor on a phone downloads all of it.",
        "Free fix path: run your URL through Google PageSpeed Insights. Takes thirty seconds and hands you the actual list of what's wrong. Send that list to whoever built your site.",
        "You do not need to understand any of it. You just need to make somebody fix it.",
        "Post your load time below and I'll tell you if it's a problem. Test it on cell, not wifi, that's the whole point."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-09-17",
      "dateLabel": "Thu, Sep 17"
    },
    {
      "id": "fb-24",
      "pillar": "Ritual",
      "headline": "I call your business on camera and tell you what I heard. Volunteers only.",
      "fb": [
        "TEARDOWN TUESDAY. Volunteers only, and I mean that.",
        "Drop your business below. I'll pick one, pull up your website and Google profile, and call your line on camera as a regular customer. Then I tell you the one thing I'd fix first, and I give you the free version of the fix even when there's a paid version.",
        "Last week's takeaway, and I'm keeping a tally: I've called nineteen businesses for these now and five answered.",
        "Five out of nineteen. In a market where everybody says it's slow and leads are expensive.",
        "The bar is on the floor out here. That's not an insult, it's the single best news in this group, because stepping over it costs almost nothing.",
        "Who's up? 👇"
      ],
      "firstComment": "Everything I post here goes deeper in the free group: {{GROUP_URL}}. No pitching, no spam, just the moves that put money back in a small business.",
      "cta": false,
      "date": "2026-09-19",
      "dateLabel": "Sat, Sep 19"
    },
    {
      "id": "fb-25",
      "pillar": "Steal This",
      "headline": "One jobsite photo is a week of posts. It's already on your phone.",
      "fb": [
        "You take before-and-after photos on every job and then do nothing with them. Four-minute fix.",
        "Drop the photo into AI and say: \"I'm a [trade] in [town]. Write a short Facebook post about this job aimed at local homeowners. No hashtags, no hype, write like a normal person talking about their work. Then give me three variations.\"",
        "One job, a week of posts.",
        "And here's why this beats any clever marketing idea you'll read this month: people don't hire you because you posted a tip. They hire you because they saw you doing the work over and over until you were the obvious person to call when the thing broke.",
        "Consistency beats cleverness, and the photos are already sitting on your phone from work you already did.",
        "One rule: read it before you post it and cut anything that sounds like a brochure. If it has the word \"solutions\" in it, start over."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-09-21",
      "dateLabel": "Mon, Sep 21"
    },
    {
      "id": "fb-26",
      "pillar": "The Leak",
      "headline": "Your best week is also your leakiest week. That's the ceiling.",
      "fb": [
        "Here's the trap nobody warns you about when you start a business.",
        "When you're slow, you answer every call on the first ring. You're helpful, you follow up, you send the quote that night.",
        "When you're slammed, which is exactly when the calls are worth the most, you're on a roof or under a sink or in somebody's chair, and the phone rings out.",
        "So your best week is also your leakiest week. And it feels great, because you're busy, and you never see the four jobs that called and went elsewhere.",
        "That's the ceiling. Your growth is capped by your own two hands, and no amount of hustle raises it, because hustle is what's already using the hands.",
        "Every business that broke through did the same thing in some form. They stopped requiring themselves to be the one who answers.",
        "Anyone else feel this one? What's your busiest day of the week and what actually happens to the phone on it?"
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-09-24",
      "dateLabel": "Thu, Sep 24"
    },
    {
      "id": "fb-27",
      "pillar": "Straight Talk",
      "headline": "What I got wrong about AI for small business.",
      "fb": [
        "Things I was wrong about, since this group is supposed to be useful and not a highlight reel.",
        "I thought owners would want to build it themselves. Give them the prompts, the tools, the how. Most don't, and it's not laziness. It's that a person doing forty things already does not want a forty-first, even a good one. The people who DO want to build it are wonderful and they're maybe one in ten.",
        "I thought the hard part was the technology. It's not, it hasn't been for a while. The hard part is that a small business's actual knowledge (your prices, your service area, your standards, the way you talk) lives entirely in the owner's head and has never been written down anywhere. That's the real work and no software skips it.",
        "I thought people wanted to save time. Mostly they want to stop feeling behind. Those sound the same and they are not. Saving an hour on a task you hate feels like nothing if the pile is still there when you look up.",
        "Still figuring it out. What have you been wrong about in your own business? The good version of that question, not the fake-humble one."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-09-26",
      "dateLabel": "Sat, Sep 26"
    },
    {
      "id": "fb-28",
      "pillar": "Steal This",
      "headline": "Record yourself doing the job once. That's your training manual.",
      "fb": [
        "You've been meaning to write down how things work here for about four years. Here's how to do it in an afternoon.",
        "Next time you do the thing, talk through it out loud and record it on your phone. Opening the shop. Running the estimate. Closing out a job. Whatever the new person always gets wrong.",
        "Then drop the recording into AI and say: \"Turn this into a step-by-step checklist a brand new employee could follow, in plain language, and flag anything I skipped or assumed.\"",
        "That last part is the gold. It catches the fifteen things you do automatically and never mention, which is exactly the stuff new hires get wrong and then get yelled at for.",
        "One afternoon, five recordings, and you have the manual you've been meaning to write since 2022.",
        "What's the one job at your company that only exists in one person's head? That's the first one to record."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-09-28",
      "dateLabel": "Mon, Sep 28"
    },
    {
      "id": "fb-29",
      "pillar": "The Leak",
      "headline": "Call your three biggest competitors tonight. You're finding out one thing.",
      "fb": [
        "Twenty-minute assignment for tonight, and it's the most useful thing you'll do this month.",
        "Call your three biggest competitors after hours, as a customer. You're finding out exactly one thing: who answers.",
        "Usually the answer is nobody, and you'll feel a lot better about yourself for about ten seconds.",
        "Sometimes one of them answers. And that one is quietly eating everybody's evening and weekend work, and the rest of the market is standing around saying it's a slow year.",
        "Then sit with the second half of this. Your customers run this exact test on you. Every single evening. They don't call you and wait, they call down the list until a human picks up, and then they stop calling.",
        "Whoever answers wins. That's not strategy, that's arithmetic.",
        "Do it tonight and report back. How many of your three picked up? I'll collect the results, I want the industry breakdown."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-10-01",
      "dateLabel": "Thu, Oct 1"
    },
    {
      "id": "fb-30",
      "pillar": "Under the Hood",
      "headline": "Thirty days, zero dollars, four afternoons. The whole list.",
      "fb": [
        "If you handed me your business for thirty days and said find money without spending any, this is the whole list, in order. Save it.",
        "WEEK 1. Find out how many calls you actually miss. Just the number, from your phone bill or your carrier app. Most owners have never looked and it is the single most upsetting number in the business.",
        "WEEK 2. Turn on missed-call text-back (it's already in the system you pay for) and fix your Google review link so it opens the review box in one tap instead of four. Both free, both an afternoon.",
        "WEEK 3. Text every quote from the last twelve months that never closed. One line: \"Did you ever get that handled?\" No pitch, no discount.",
        "WEEK 4. Paste all your bad reviews into AI at once and ask for the single most common pattern. Fix that one thing. It's almost never what you've been defending, it's almost always communication.",
        "Zero dollars. Four afternoons. And it's more than most businesses will do all year, which is the entire reason it works.",
        "Start with week one. Post your missed-call number when you find it. I promise you it's worse than you think, and I promise you're not the only one."
      ],
      "firstComment": null,
      "cta": false,
      "date": "2026-10-03",
      "dateLabel": "Sat, Oct 3"
    }
  ],
  "group": [
    {
      "label": "Group name",
      "lines": [
        "Main Street AI: AI Hacks for Small Business Owners"
      ]
    },
    {
      "label": "Description",
      "lines": [
        "Practical AI for people who run real businesses.",
        "No theory, no crypto-bro hype, no \"10x your mindset.\" Just the specific moves that put money back in a small business: the calls you're missing, the follow-ups you're not sending, the paperwork eating your Sunday.",
        "Free. Always. You'll get:",
        "• Teardown Tuesday. I take one real member business and find the money leak on video, free",
        "• Steal This Thursday. One AI move you can run today, no tools, no budget",
        "• Straight answers when you ask. Post your question, I answer it.",
        "Run by Sarah at Modern Mustard Seed. We build AI staff for Main Street businesses. But this group is not a sales pitch. If you never buy anything, you should still leave with more money than you came in with.",
        "Rules in the pinned post. Come in, tell us what you do, and steal everything that isn't nailed down."
      ]
    },
    {
      "label": "Join questions",
      "lines": [
        "1. What's your business, and how long have you been running it? (qualifies real owners, kills spam)",
        "2. What's the one thing in your week that eats the most time and makes the least money? (this is your content research engine AND your sales intel, forever)",
        "3. Want the weekly Main Street AI move sent to you? Drop your email. (optional). This builds an owned email list for free. Facebook can change the rules on your group tomorrow. It cannot take your list."
      ]
    },
    {
      "label": "Rules",
      "lines": [
        "1. No pitching in posts. Ever. Not yours, not mine. Answer questions and people will find you.",
        "2. No link drops without context. Explain the thing, then link it if someone asks.",
        "3. Real questions get real answers. Ask specific (\"my HVAC company misses calls during install days\") not vague (\"how do I use AI\").",
        "4. No DM pitching members. One report and you're out. This rule is why the group stays worth being in.",
        "5. Share what worked. If you steal something here and it made you money, come back and say so. That's rent."
      ]
    },
    {
      "label": "Pinned \"Start Here\" post",
      "lines": [
        "Welcome, Main Streeter.",
        "Here's what this place is for. You run a real business. You keep hearing you should \"use AI\" and every article you find was written for a software company with a marketing department. This group is the translation.",
        "Start with these three, in order. They cost nothing and they're the highest-return moves for almost any small business:",
        "1. Call your own business right now. From your cell phone. After hours. Listen to the whole thing the way a customer would. Most owners have never done this and most are horrified. That is your baseline.",
        "2. Turn on missed-call text-back. If a call goes unanswered, an automatic text goes out inside 60 seconds: \"Sorry we missed you, this is [Business], what do you need?\" Almost every phone system and CRM does this and most owners never turned it on. It is the highest-ROI switch in small business.",
        "3. Fix your review link. Stop sending customers to your homepage. Send them to the link that opens the Google review box directly. That one extra tap is where your reviews go to die.",
        "Do those three this week. Then post here and tell me what happened.",
        "Weekly rhythm:",
        "Tuesday: Teardown Tuesday. Comment your business, I pick one and find the leak on video. Free.",
        "Thursday: Steal This. One move, run it today.",
        "Friday: Win Friday. Post what worked this week. Big or small.",
        "Ask me anything in here. I answer everything."
      ]
    }
  ],
  "tactics": [
    {
      "head": "Invite everyone who reacts to your posts to follow the Page",
      "body": "Click the reaction count, then \"Invite.\" Facebook still lets you do this and it is the most underused free follower source on the platform. 30 seconds per post. Do it on every post that gets more than 5 reactions. This alone can be a few hundred followers in your first month."
    },
    {
      "head": "Own the first 60 minutes",
      "body": "Facebook decides how far to push a post largely on early engagement. Post, then stay on your phone for an hour and reply to every comment. Reply with a question, so they reply again. Two comments from one person is double the signal."
    },
    {
      "head": "Reels: hook in 1.5 seconds",
      "body": "Not 3. The first frame has to make a scrolling thumb stop. Lead with the most surprising fact, not with \"Hey guys.\""
    },
    {
      "head": "Text on screen, always",
      "body": "Most Facebook video is watched muted, mid-scroll, one-handed. If your point only exists in the audio, it does not exist."
    },
    {
      "head": "20 to 40 seconds",
      "body": "Watch-through rate is the dominant Reels ranking input. A 25-second Reel watched twice beats a 90-second Reel abandoned at 20 seconds. Cut ruthlessly."
    },
    {
      "head": "Post Reels natively from the phone, not through Blotato",
      "body": "Trending audio and the in-app Reels editor are only available in the app, and audio selection is a real distribution lever. Schedule the *text* posts through the API. Shoot and post the Reels by hand."
    },
    {
      "head": "No naked links in the post body",
      "body": "Link in the first comment. Every time. This one costs people 70% of their reach and they never find out."
    },
    {
      "head": "Serve in 10 other groups, 10 minutes a day",
      "body": "This is the entire cold-start plan for weeks 1 through 4. Find groups where SMB owners ask questions. Answer with a genuinely complete answer and no link and no pitch. Your profile does the selling. People click the name of whoever helped them."
    },
    {
      "head": "Go Live once a week, 20 minutes",
      "body": "Facebook pushes Live to followers harder than anything else. Take questions from the Group. This converts members to buyers faster than any post will."
    },
    {
      "head": "Repurpose on a 3-week delay",
      "body": "Every Reel becomes a text post three weeks later. Every text post that outperforms becomes a Reel. Nobody saw it the first time."
    }
  ]
} as const;
export type FbPlaybook = typeof FB_PLAYBOOK;
