// GENERATED by scripts/gen-pictures-frames.mjs. Do not edit by hand.
// Which MUSTARD PICTURES hero frames have been pre-rendered on Codex.
export const RENDERED_FRAMES: readonly string[] = ["home-services","restaurant","beauty","fitness","retail","professional","health","other"] as const;
