import fs from 'node:fs';
import { createClient } from '@supabase/supabase-js';
const env = Object.fromEntries(fs.readFileSync('.env.local','utf8').split(/\r?\n/).filter(l=>/^[A-Z_]+=/.test(l)).map(l=>{const i=l.indexOf('=');return [l.slice(0,i),l.slice(i+1).replace(/^"|"$/g,'')];}));
const sb = createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);
const { data } = await sb.from('app_state').select('key,value,updated_at').eq('key','llm_worker_health').maybeSingle();
console.log('llm_worker_health:', JSON.stringify(data)?.slice(0,300));
const { data: b } = await sb.storage.listBuckets();
console.log('buckets:', (b??[]).map(x=>`${x.name}${x.public?'(public)':''}`).join(', '));
const { data: j } = await sb.from('llm_jobs').select('id,status,created_at,finished_at').order('created_at',{ascending:false}).limit(3);
console.log('recent llm_jobs:', JSON.stringify(j));
