-- Lead Tracker: create the table and seed Polly's first 97 Flathead Valley prospects.
-- Real businesses + phone numbers from OpenStreetMap. Paste this whole file into
-- the Supabase SQL editor (project qqvohlvhynmtavdbvkha) and run it once.
create table if not exists public.rep_prospects (
  id uuid primary key default gen_random_uuid(),
  rep_email text not null, rep_name text,
  business text not null, city text, phone text,
  channel text not null default 'cold-call',
  status text not null default 'to-contact',
  notes text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create index if not exists rep_prospects_rep_idx on public.rep_prospects (rep_email);
create index if not exists rep_prospects_status_idx on public.rep_prospects (status);
create index if not exists rep_prospects_city_idx on public.rep_prospects (city);
alter table public.rep_prospects disable row level security;

insert into public.rep_prospects (rep_email, rep_name, business, city, phone, channel, status, notes) values
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Glacier Medical Associates', 'Whitefish', '(406) 862-2515', 'cold-call', 'to-contact', 'Clinic (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'MacKenzie River Pizza Co', 'Whitefish', '(406) 862-6601', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Craggy Range Bar & Grill', 'Whitefish', '(406) 862-7550', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Great Northern Bar & Grill', 'Whitefish', '(406) 862-2816', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Straight Blast Gym Martial Arts Kalispell', 'Kalispell', '(406) 752-7244', 'cold-call', 'to-contact', 'Gym (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'The Yoga Room of Montana', 'Kalispell', '(406) 752-7244', 'cold-call', 'to-contact', 'Gym (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Tupelo Grille', 'Whitefish', '(406) 862-6136', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Cowgirl Coffee', 'Whitefish', '(406) 862-6911', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'China Wall Restaurant', 'Whitefish', '(406) 862-2604', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Thai Palace', 'Kalispell', '(406) 756-7956', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Logan Health Primary Care', 'Kalispell', '(406) 752-8433', 'cold-call', 'to-contact', 'Clinic (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Stillwater Fish House', 'Whitefish', '(406) 730-1230', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Integrity Property Management, Inc.', 'Kalispell', '(406) 755-6336', 'cold-call', 'to-contact', 'Real estate (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Bias Brewing', 'Kalispell', '(406) 730-3020', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Amazing Crepes', 'Whitefish', '(406) 862-6002', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Flathead Health & Fitness', 'Kalispell', '(406) 752-2438', 'cold-call', 'to-contact', 'Gym (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Hop''s Downtown Grill', 'Kalispell', '(406) 755-7687', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Loula''s Cafe', 'Whitefish', '(406) 862-5614', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Access Fitness Evergreen', 'Kalispell', '(406) 890-2210', 'cold-call', 'to-contact', 'Gym (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Pho Ly Asian Cuisine', 'Kalispell', '(406) 205-3128', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Panda Express', 'Kalispell', '(406) 752-0386', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Bonelli''s Bistro', 'Kalispell', '(406) 257-8669', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Copper Mountain Coffee', 'Kalispell', '(406) 257-1326', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Scotty''s Bar', 'Kalispell', '(406) 257-8188', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'MOD Pizza', 'Kalispell', '(406) 300-5737', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Dickey''s Barbecue Pit', 'Kalispell', '(406) 300-1375', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Nickerbokker''s Pizza Company', 'Kalispell', '(406) 260-4729', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Ulta Beauty', 'Kalispell', '(406) 756-0907', 'cold-call', 'to-contact', 'Salon / spa (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Kobe Steak & Sushi', 'Kalispell', '(406) 314-6195', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Frugals', 'Kalispell', '(406) 890-2444', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Sable Coffee', 'Kalispell', '(406) 260-4173', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Jalisco Cantina', 'Whitefish', '(406) 862-6223', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Saigon Garden', 'Kalispell', '(406) 755-5290', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Florence Coffee Company', 'Kalispell', '(406) 890-0125', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Papa Murphy''s', 'Kalispell', '(406) 257-8787', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Chi Cafe', 'Kalispell', '(406) 407-7707', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Taco John''s', 'Kalispell', '(406) 755-3140', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'The Desoto Grill', 'Kalispell', '(406) 314-6095', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', '4B''s Restaurant', 'Kalispell', '(406) 314-6266', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Chinatown', 'Kalispell', '(406) 755-2401', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Bojangles''', 'Kalispell', '(406) 755-3222', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'The Allergy & Asthma Center, P.C', 'Kalispell', '(406) 300-4882', 'cold-call', 'to-contact', 'Clinic (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Cislo''s Family Restaurant', 'Kalispell', '(406) 756-7330', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Evergreen Clinic', 'Kalispell', '(406) 756-7225', 'cold-call', 'to-contact', 'Clinic (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Norm''s Soda Fountain', 'Kalispell', '(406) 756-5466', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Eagle''s Club & Lounge', 'Kalispell', '(406) 752-7265', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'The Alley Connection', 'Kalispell', '(406) 752-7077', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Brannigan''s Irish Pub', 'Kalispell', '(406) 393-2418', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Moose''s Saloon', 'Kalispell', '(406) 755-2337', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Haus Beauty Lounge', 'Kalispell', '(406) 755-7254', 'cold-call', 'to-contact', 'Salon / spa (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'DQ Grill & Chill', 'Kalispell', '(406) 755-2955', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Agave Cantina', 'Kalispell', '(406) 756-3600', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'The Willow Salon', 'Kalispell', '(406) 890-3915', 'cold-call', 'to-contact', 'Salon / spa (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Scoreboard Pub', 'Kalispell', '(406) 756-8888', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Kalispell Volkswagon & BMW Service', 'Kalispell', '(406) 380-4255', 'cold-call', 'to-contact', 'Auto shop (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Cron Automotive', 'Kalispell', '(406) 755-5747', 'cold-call', 'to-contact', 'Auto shop (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Food for the Soul', 'Kalispell', '(406) 407-6191', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'The House of S&M', 'Kalispell', '(406) 309-5541', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Wheat Montana Bakery and Deli', 'Kalispell', '(406) 257-6530', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Est.1989 Salon and Spa', 'Kalispell', '(406) 314-6191', 'cold-call', 'to-contact', 'Salon / spa (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'The Knead Cafe', 'Kalispell', '(406) 755-3883', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Blue Samurai', 'Kalispell', '(406) 890-2583', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Colter Coffee', 'Kalispell', '(406) 407-0235', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Bella Italia Ristorante', 'Kalispell', '(406) 890-7800', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'The Montana Club', 'Kalispell', '(406) 260-4401', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Nickel Charlie''s', 'Kalispell', '(406) 257-7756', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'KM Bar', 'Kalispell', '(406) 602-5613', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Mercantile Steak', 'Kalispell', '(406) 300-0808', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Berkshire Hathaway HomeServices', 'Kalispell', '(406) 309-6330', 'cold-call', 'to-contact', 'Real estate (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Artistic Barbering', 'Kalispell', '(406) 755-1353', 'cold-call', 'to-contact', 'Salon / spa (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Sykes Diner', 'Kalispell', '(406) 257-4304', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'SunRift Beer Company', 'Kalispell', '(406) 309-2627', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Casa Mexico', 'Kalispell', '(406) 752-6800', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'MacKenzie River Pizza', 'Kalispell', '(406) 756-0060', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Ranger Joe''s Pizza', 'Kalispell', '(406) 300-1616', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Angela''s Pizza', 'Kalispell', '(406) 755-4444', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Mud Man Burgers', 'Kalispell', '(406) 300-0286', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'VFW Post 2252', 'Kalispell', '(406) 752-2611', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Taco Del Sol', 'Kalispell', '(406) 755-7775', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'LayLa Threading', 'Kalispell', '(406) 257-2588', 'cold-call', 'to-contact', 'Salon / spa (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Jo Mama''s Coffee', 'Kalispell', '(406) 249-7990', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Whitefish Handcrafted Spirits', 'Kalispell', '(406) 890-2300', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Buffalo Wild Wings', 'Kalispell', '(406) 407-7500', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Kalispell Nails', 'Kalispell', '(406) 756-6789', 'cold-call', 'to-contact', 'Salon / spa (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Applebee''s', 'Kalispell', '(406) 755-5575', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Chick-fil-A', 'Kalispell', '(406) 752-3710', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Logan Health Orthopedics & Sports Medicine - Sunnyview', 'Kalispell', '(406) 752-7900', 'cold-call', 'to-contact', 'Clinic (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Hungry Hun', 'Kalispell', '(406) 250-1128', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Flathead Animal Clinic', 'Kalispell', '(406) 755-5046', 'cold-call', 'to-contact', 'Vet (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'A-Plus Health Care', 'Kalispell', '(406) 755-4968', 'cold-call', 'to-contact', 'Clinic (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Kalispell Toyota Servive', 'Kalispell', '(406) 756-4770', 'cold-call', 'to-contact', 'Auto shop (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Mac and Dun''s Mountain Bites', 'Kalispell', '(406) 897-0600', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Bamboo Express', 'Kalispell', '(406) 897-0641', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Hokkaido Ramen House', 'Kalispell', '(406) 309-2485', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Huck’s Place', 'Whitefish', '(406) 909-0551', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Stageline Pizza', 'Columbia Falls', '(406) 892-3288', 'cold-call', 'to-contact', 'Restaurant (OpenStreetMap, confirm number when you call)'),
('thompsonpolly71@gmail.com', 'Polly Thompson', 'Glacier Garage', 'Kalispell', '(406) 920-9065', 'cold-call', 'to-contact', 'Auto shop (OpenStreetMap, confirm number when you call)');
