#!/usr/bin/env node
/**
 * Config as code for every Vapi assistant.
 *
 *   node scripts/vapi-sync.mjs --pull            snapshot live -> vapi/assistants/*.json
 *   node scripts/vapi-sync.mjs --diff            what differs, repo vs live (exit 1 on drift)
 *   node scripts/vapi-sync.mjs --push <slug>     apply one config to Vapi
 *   node scripts/vapi-sync.mjs --push --all      apply every config
 *
 * WHY THIS EXISTS
 * Eight client concierges lived only inside the Vapi dashboard. No history, no
 * review, no rebuild path: one bad edit or delete and a paying client's phone
 * agent was gone with nothing to restore from. This puts every assistant in git
 * where changes are diffable and revertable, and makes drift detectable in CI.
 *
 * Needs the PRIVATE VAPI_API_KEY. The public key cannot read or write assistants.
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONFIG_DIR = resolve(__dirname, '../vapi/assistants');

function loadEnvFile(path) {
  try {
    const out = {};
    for (const line of readFileSync(path, 'utf8').split(/\r?\n/)) {
      const m = /^([A-Z0-9_]+)\s*=\s*(.*)$/.exec(line.trim());
      if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
    return out;
  } catch {
    return {};
  }
}

const fileEnv = {
  ...loadEnvFile(resolve(__dirname, '../../modern-mustard-seed-voice-agent/.env')),
  ...loadEnvFile(resolve(__dirname, '../.env.local')),
};

// `vercel env pull` writes this literal for Sensitive vars, which are write-only
// in Vercel forever. It is truthy, so it must be filtered or it lands in an
// Authorization header and returns a baffling 401.
const PLACEHOLDER = '[SENSITIVE]';
const env = (k) => {
  const v = process.env[k] ?? fileEnv[k];
  return v === PLACEHOLDER ? undefined : v;
};

const VAPI_API_KEY = env('VAPI_API_KEY');

/* ── Ownership ────────────────────────────────────────────────────────
 * Mr. Mustard is NOT managed here. His config is generated by
 * setup-vapi-mustard.mjs, which derives his spoken prices from the same
 * TypeScript that bills the customer. Snapshotting him into a static JSON would
 * freeze those prices and quietly reintroduce hand-typed pricing, which is the
 * exact failure that script exists to prevent. He is still DIFFED here so drift
 * stays visible, he is just never pushed from a snapshot. */
const OWNED_ELSEWHERE = {
  'faf7f2c4-9cfd-4fcd-9c1a-73b7c9a38eee': 'setup-vapi-mustard.mjs',
};

/* Fields we manage. Everything else Vapi returns (id, orgId, createdAt,
 * updatedAt, isServerUrlSecretSet, latestVersion) is server-owned bookkeeping
 * and must never be written back, or a push starts fighting the API. */
const MANAGED = [
  'name', 'firstMessage', 'model', 'voice', 'transcriber', 'server',
  'serverMessages', 'endCallPhrases', 'endCallMessage', 'analysisPlan',
  'backgroundSound', 'backgroundSpeechDenoisingPlan', 'backgroundDenoisingEnabled',
  'startSpeakingPlan', 'stopSpeakingPlan', 'maxDurationSeconds',
  'silenceTimeoutSeconds', 'recordingEnabled', 'metadata', 'voicemailDetection',
  'voicemailMessage', 'firstMessageMode', 'clientMessages', 'compliancePlan',
];

const slugify = (name) =>
  (name || 'unnamed')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);

/* ⚠️ SECRETS COME BACK INSIDE `model.tools[]`. Vapi hides the assistant-level
 * server.secret on a GET, which makes it easy to assume no secret is ever
 * returned. That is wrong: each TOOL carries its own server block, and those
 * secrets ARE returned in full. A naive pull wrote a live webhook secret
 * straight into a JSON file destined for a public repo (caught 2026-08-11 by a
 * pre-commit scan, before it reached git).
 *
 * So every value under a secret-ish key is stripped on the way in. Both sides
 * are scrubbed before diffing, or the repo would look permanently drifted, and
 * --push puts the live values back at the same paths so stripping them here
 * never clears them there. */
const SECRET_KEYS = new Set(['secret', 'apikey', 'token', 'authorization', 'password']);

function scrub(v) {
  if (Array.isArray(v)) return v.map(scrub);
  if (v && typeof v === 'object') {
    return Object.fromEntries(
      Object.entries(v)
        .filter(([k]) => !SECRET_KEYS.has(k.toLowerCase()))
        .map(([k, val]) => [k, scrub(val)])
    );
  }
  return v;
}

// Walks config beside live and puts back any secret the scrub removed, so a
// push preserves webhook auth it can no longer see.
function restoreSecrets(cfg, live) {
  if (!live || typeof live !== 'object' || !cfg || typeof cfg !== 'object') return cfg;
  if (Array.isArray(cfg)) return cfg.map((item, i) => restoreSecrets(item, Array.isArray(live) ? live[i] : undefined));
  const out = { ...cfg };
  for (const [k, v] of Object.entries(live)) {
    if (SECRET_KEYS.has(k.toLowerCase()) && out[k] === undefined) out[k] = v;
    else if (out[k] !== undefined) out[k] = restoreSecrets(out[k], v);
  }
  return out;
}

// Unscrubbed, secrets intact. Only --push uses this, only in memory, only to
// put back what the scrub removed. Never write its output to disk.
function managedOnlyRaw(a) {
  const out = {};
  for (const k of MANAGED) if (a[k] !== undefined) out[k] = a[k];
  return out;
}

function managedOnly(a) {
  return scrub(managedOnlyRaw(a));
}

// Stable key order so a pull produces no spurious git diff on unchanged agents.
function sortKeys(v) {
  if (Array.isArray(v)) return v.map(sortKeys);
  if (v && typeof v === 'object') {
    return Object.fromEntries(Object.keys(v).sort().map((k) => [k, sortKeys(v[k])]));
  }
  return v;
}

async function vapi(path, init) {
  const res = await fetch(`https://api.vapi.ai${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${VAPI_API_KEY}`,
      ...(init?.body ? { 'Content-Type': 'application/json' } : {}),
    },
  });
  const body = await res.json().catch(() => null);
  if (!res.ok) {
    // Thrown rather than exited, for the libuv reason described above main().
    const hint = res.status === 401 ? '\nA 401 here usually means the PUBLIC key is in VAPI_API_KEY. Use the private one.' : '';
    throw new Error(`Vapi ${init?.method || 'GET'} ${path} failed (${res.status}): ${body?.message || res.statusText}${hint}`);
  }
  return Array.isArray(body) ? body : (body?.results ?? body);
}

/* Path-based deep diff. Reports WHERE things differ rather than dumping two
 * objects, because a 22k character prompt makes a raw dump unreadable. */
function diff(a, b, path = '', out = []) {
  const isObj = (v) => v && typeof v === 'object' && !Array.isArray(v);
  if (isObj(a) && isObj(b)) {
    for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) {
      diff(a[k], b[k], path ? `${path}.${k}` : k, out);
    }
  } else if (JSON.stringify(a) !== JSON.stringify(b)) {
    const show = (v) => {
      if (v === undefined) return '(absent)';
      const s = typeof v === 'string' ? v : JSON.stringify(v);
      return s.length > 70 ? `${s.slice(0, 70)}... (${s.length} chars)` : s;
    };
    out.push({ path, repo: show(a), live: show(b) });
  }
  return out;
}

const args = process.argv.slice(2);
const has = (f) => args.includes(f);

// An assistant with neither a prompt nor tools is a leftover voice-sampling
// probe, not an agent. Tracking them would enshrine junk and make diffs noisy.
const isReal = (a) => (a.model?.messages ?? []).some((m) => m.content) || (a.model?.tools ?? []).length > 0;

function readConfigs() {
  if (!existsSync(CONFIG_DIR)) return [];
  return readdirSync(CONFIG_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => ({ slug: f.replace(/\.json$/, ''), ...JSON.parse(readFileSync(join(CONFIG_DIR, f), 'utf8')) }));
}

async function pull() {
  mkdirSync(CONFIG_DIR, { recursive: true });
  const live = await vapi('/assistant?limit=1000');
  const real = live.filter(isReal);

  for (const a of real) {
    const body = { id: a.id, ...sortKeys(managedOnly(a)) };
    if (OWNED_ELSEWHERE[a.id]) body._generatedBy = OWNED_ELSEWHERE[a.id];
    const json = JSON.stringify(body, null, 2) + '\n';

    /* Belt and braces. The scrub above is keyed on a fixed list of field names,
     * so a future Vapi field called something else would slip past it and land
     * in a public repo. This catches anything that still looks like a credential
     * and refuses to write the file at all. Failing the pull is cheap; leaking a
     * client's webhook secret into git history is not. */
    const leak = /"(?:[a-z]*secret|apiKey|token|authorization|password)"\s*:\s*"[^"]+"/i.exec(json);
    if (leak) {
      throw new Error(
        `Refusing to write ${slugify(a.name)}.json: it still contains ${leak[0].split(':')[0]}.\n` +
          `Add that field name to SECRET_KEYS in this script before pulling again.`
      );
    }
    writeFileSync(join(CONFIG_DIR, `${slugify(a.name)}.json`), json);
  }

  console.log(`\nPulled ${real.length} assistant(s) into vapi/assistants/`);
  const skipped = live.length - real.length;
  if (skipped) console.log(`Skipped ${skipped} empty probe assistant(s) with no prompt and no tools.`);
  console.log(`\nReview with \`git diff\`, then commit. Nothing was written to Vapi.\n`);
}

async function runDiff() {
  const configs = readConfigs();
  if (!configs.length) {
    throw new Error('No configs in vapi/assistants/. Run --pull first.');
  }

  const live = await vapi('/assistant?limit=1000');
  const liveById = new Map(live.map((a) => [a.id, a]));
  let drifted = 0;

  for (const cfg of configs) {
    const found = liveById.get(cfg.id);
    if (!found) {
      console.log(`\n${cfg.slug}\n  GONE FROM VAPI. Config in repo, no assistant with id ${cfg.id}.`);
      drifted++;
      continue;
    }
    const { id, _generatedBy, slug, ...want } = cfg;
    const changes = diff(want, sortKeys(managedOnly(found)));
    if (changes.length) {
      drifted++;
      console.log(`\n${slug}${_generatedBy ? `  (generated by ${_generatedBy})` : ''}`);
      for (const c of changes) console.log(`  ${c.path}\n    repo: ${c.repo}\n    live: ${c.live}`);
    }
  }

  const tracked = new Set(configs.map((c) => c.id));
  const untracked = live.filter((a) => !tracked.has(a.id) && isReal(a));
  if (untracked.length) {
    console.log(`\n${untracked.length} live assistant(s) not tracked in the repo:`);
    for (const a of untracked) console.log(`  ${a.name || a.id}`);
    drifted++;
  }

  console.log(drifted ? `\n${drifted} item(s) drifted.\n` : `\nIn sync. Repo matches Vapi.\n`);
  process.exitCode = drifted ? 1 : 0;
}

async function push() {
  const configs = readConfigs();
  const targets = has('--all') ? configs : configs.filter((c) => c.slug === args[args.indexOf('--push') + 1]);

  if (!targets.length) {
    throw new Error(`Nothing to push. Give a slug or --all. Available:\n  ${configs.map((c) => c.slug).join('\n  ') || '(none, run --pull)'}`);
  }

  for (const cfg of targets) {
    if (OWNED_ELSEWHERE[cfg.id]) {
      console.log(`\nSKIP ${cfg.slug}: owned by ${OWNED_ELSEWHERE[cfg.id]}.`);
      console.log(`  Pushing a snapshot would freeze prices this agent derives at build time.`);
      continue;
    }

    const { id, _generatedBy, slug, ...stored } = cfg;
    const found = await vapi(`/assistant/${id}`);
    // Put back the tool-level secrets stripped on pull, so a push never
    // silently unauthenticates a webhook it could not see.
    const body = restoreSecrets(stored, managedOnlyRaw(found));

    /* A PATCH carrying `server` WITHOUT a secret clears any secret already set,
     * silently unauthenticating a webhook that was protected. Configs never hold
     * secrets (they are committed to git), so `server` is dropped from the patch
     * whenever live already has one. Set webhook secrets in the Vapi dashboard. */
    if (found.isServerUrlSecretSet && body.server && body.server.secret === undefined) {
      delete body.server;
      console.log(`  ${slug}: leaving server untouched, it has a webhook secret this push would clear.`);
    }

    await vapi(`/assistant/${id}`, { method: 'PATCH', body: JSON.stringify(body) });
    console.log(`  pushed ${slug}`);
  }
  console.log(`\nDone. Run --diff to confirm.\n`);
}

/* Commands set process.exitCode rather than calling process.exit(). On Windows,
 * process.exit() while fetch's async handles are still closing trips a libuv
 * assertion (!(handle->flags & UV_HANDLE_CLOSING)) and the process dies with 127
 * INSTEAD of the code we meant to return. CI reads that exit code to decide
 * whether the fleet drifted, so a bogus 127 would make every check look broken. */
async function main() {
  if (!VAPI_API_KEY) {
    throw new Error(
      `No usable VAPI_API_KEY.\n\n` +
        `Vapi vars pulled by \`vercel env pull\` are the literal "${PLACEHOLDER}"\n` +
        `placeholder, because Sensitive vars in Vercel are write-only forever.\n` +
        `Put the PRIVATE key from the Vapi dashboard into .env.local.`
    );
  }

  if (has('--pull')) return pull();
  if (has('--diff')) return runDiff();
  if (has('--push')) return push();

  console.log(`
Config as code for Vapi assistants.

  --pull          snapshot live assistants into vapi/assistants/
  --diff          show drift between repo and live (exit 1 if any)
  --push <slug>   apply one config
  --push --all    apply every config

Mr. Mustard is diffed but never pushed here: setup-vapi-mustard.mjs owns him.
`);
}

await main().catch((err) => {
  console.error(`\n${err.message}\n`);
  process.exitCode = 1;
});
