import {createRequire} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright');const sharp=require('sharp');
const data=async(name,type)=>`data:${type};base64,${(await readFile('public/flathead/'+name)).toString('base64')}`;
const [scene,boat,font,italic,body,bold]=await Promise.all([data('flathead-handmade-1536.jpg','image/jpeg'),data('mustard-sailboat-768.webp','image/webp'),data('instrument-serif.woff2','font/woff2'),data('instrument-serif-italic.woff2','font/woff2'),data('manrope.woff2','font/woff2'),data('manrope-bold.woff2','font/woff2')]);
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1200,height:630},deviceScaleFactor:1});
// Text messages shrink the card to a thumbnail, so the copy sits white and large on a frosted, blurred panel of the scene itself.
await page.setContent(`<style>@font-face{font-family:Display;src:url(${font})}@font-face{font-family:Display;src:url(${italic});font-style:italic}@font-face{font-family:Body;src:url(${body})}@font-face{font-family:Body;src:url(${bold});font-weight:700}*{box-sizing:border-box}body{margin:0;background:#103c54;color:#fff;width:1200px;height:630px;overflow:hidden}.scene{position:absolute;inset:0;width:1200px;height:630px;object-fit:cover;object-position:center 58%}.glass{position:absolute;top:0;left:0;bottom:0;width:780px;backdrop-filter:blur(24px) saturate(1.1);background:linear-gradient(90deg,rgba(8,34,52,.70) 0%,rgba(8,34,52,.58) 70%,rgba(8,34,52,.30) 100%);-webkit-mask-image:linear-gradient(90deg,#000 80%,transparent 100%);mask-image:linear-gradient(90deg,#000 80%,transparent 100%)}.copy{position:absolute;top:0;bottom:0;left:70px;width:680px;display:flex;flex-direction:column;justify-content:center;text-shadow:0 2px 18px rgba(0,0,0,.35)}.brand{font:700 22px Body;letter-spacing:.2em;text-transform:uppercase;color:#F5B700}h1{font:108px/1 Display;margin:22px 0 0;letter-spacing:-.02em}.line{font:26px/1.35 Body;margin-top:30px;color:rgba(255,255,255,.94)}.boat{position:absolute;width:230px;right:110px;bottom:56px;filter:drop-shadow(0 10px 18px rgba(0,0,0,.25))}</style><img class="scene" src="${scene}"><div class="glass"></div><div class="copy"><div class="brand">Modern Mustard Seed</div><h1>Build what’s next.<br><em>Grow what works.</em></h1><div class="line">AI systems, websites, and products.<br>Built in Montana.</div></div><img class="boat" src="${boat}">`);
await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(image=>image.decode()))});
const png=await page.screenshot();await writeFile('public/brand/mms-share-flathead.jpg',await sharp(png).jpeg({quality:88,mozjpeg:true}).toBuffer());await writeFile('qa/flathead/share.png',png);await browser.close();
console.log('Share card rendered at 1200 by 630.');
